services:
  inventree-db:
    image: postgres:17
    container_name: inventree-db
    expose:
      - "5432"
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdb
      - POSTGRES_USER=${INVENTREE_DB_USER}
      - POSTGRES_PASSWORD=${INVENTREE_DB_PASSWORD}
      - POSTGRES_DB=${INVENTREE_DB_NAME}
    volumes:
      - inventree_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  inventree-cache:
    image: redis:7-alpine
    container_name: inventree-cache
    env_file:
      - .env
    expose:
      - "6379"
    volumes:
      - inventree_redis_data:/data
    restart: always

  inventree-server:
    image: inventree/inventree:${INVENTREE_TAG:-stable}
    container_name: inventree-server
    expose:
      - "8000"
    depends_on:
      - inventree-db
      - inventree-cache
    env_file:
      - .env
    environment:
      INVENTREE_SERVER: http://inventree-server:8000
    volumes:
      - inventree_data:/home/inventree/data
    restart: unless-stopped

  inventree-worker:
    image: inventree/inventree:${INVENTREE_TAG:-stable}
    container_name: inventree-worker
    command: invoke worker
    depends_on:
      - inventree-server
    env_file:
      - .env
    volumes:
      - inventree_data:/home/inventree/data
    restart: unless-stopped

  inventree-proxy:
    image: caddy:alpine
    container_name: inventree-proxy
    restart: always
    depends_on:
      - inventree-server
    expose:
      - "80"
    env_file:
      - .env
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - inventree_data:/var/www:ro
      - inventree_caddy_data:/data
      - inventree_caddy_config:/config

volumes:
  inventree_postgres_data:
  inventree_redis_data:
  inventree_data:
  inventree_caddy_data:
  inventree_caddy_config:
